//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cybereum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_task()
        {
            this.tbl_subtask = new HashSet<tbl_subtask>();
        }
    
        public int taskid { get; set; }
        public string taskname { get; set; }
        public int isactive { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public int statusid { get; set; }
        public int createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public int projectid { get; set; }
        public int priority { get; set; }
        public Nullable<int> tasktypeid { get; set; }
        public int assignedto { get; set; }
        public int milestoneid { get; set; }
    
        public virtual tbl_milestone tbl_milestone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_subtask> tbl_subtask { get; set; }
        public virtual tbl_user tbl_user { get; set; }
        public virtual tbl_tasktype tbl_tasktype { get; set; }
    }
}
